Add `USERNAME` and `EMAIL` env variables
s0/git-publish-subdir-action pull request #75
Opened 2022-07-29 07:12 UTC by ozaner

Added support for a custom username and email to be used in the autogenerated commit. Just set `USERNAME` and `EMAIL` respectively in the env variables.

## Context
The autogenerated commit this action produces always uses the username and email of the pusher. This commit adds support for changing these variables using the `USERNAME` and `EMAIL` environment variables. My particular use case was to mark these autogenerated commits as being created by the github-actions bot:

```yaml
- name: Commit to Output
  uses: s0/git-publish-subdir-action@develop
  env:
    REPO: self
    BRANCH: output
    FOLDER: outputDir
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    USERNAME: "github-actions[bot]"
    EMAIL: "github-actions[bot]@users.noreply.github.com"
```

## Checklist
- [x] Change meets or does not compromise the [Baseline Security Requirements](https://transferwise.atlassian.net/wiki/spaces/EKB/pages/434929973/Baseline+Security+Requirements)

2022-07-31 18:08 UTC, s0 commented
Hiya, thanks for the contribution, this is a nice addition.

Before we can get this merged in though, we need to add a few things to this PR:

* [ ] Update the README with instructions on how to use these parameters.
* [ ] Regenerate the action code (run `npm run build` from `action/`).
* [ ] Add unit-tests that cover the use of these parameters.

I can help you with any of the above or do it myself, but happy to let you have a go if you'd prefer to do it?

2022-08-02 13:39 UTC, ozaner commented
I've updated the readme, regenerated the action code, and added a unit test. Not too familiar with typescript (or even javascript) so I might be missing something.

2022-08-22 11:24 UTC, promise commented
@s0 bump

2022-08-22 11:37 UTC, s0 requested changes
Hi! Thanks so much for this contribution, and for the docs and tests too, and sorry for the delayed review. I have some comments regarding naming, but other than this I think it's good to go! Thanks!

2022-08-22 11:37 UTC, s0 commented on action/src/index.ts
> +  EMAIL?: string;
Can we change `EMAIL` to `COMMIT_EMAIL`

2022-08-22 11:37 UTC, s0 commented on action/src/index.ts
> +  USERNAME?: string;
Can we change `USERNAME` to `COMMIT_NAME`

2022-08-23 07:50 UTC, s0 commented
(also sorry for not I clouding these change requests in the first review, I had some time to think about the naming and only remembered after I saw it in my notifications again)

2022-08-25 13:12 UTC, ozaner commented
The `USERNAME` and `EMAIL` env variables have been renamed, and the readme updated.

2022-09-27 01:54 UTC, closed without merging